<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {

        DB::statement('SET FOREIGN_KEY_CHECKS=0');


        DB::table('review_likes')->truncate();
        DB::table('reviews')->truncate();
        DB::table('contents')->truncate();
        DB::table('users')->truncate();
        DB::table('roles')->truncate();
        DB::table('sessions')->truncate();
        DB::table('personal_access_tokens')->truncate();


        DB::statement('SET FOREIGN_KEY_CHECKS=1');


        DB::table('roles')->insert([
            ['id' => 1, 'name' => 'admin', 'description' => 'Administrator', 'created_at' => '2025-10-19 08:55:02', 'updated_at' => '2025-10-19 08:55:02'],
            ['id' => 2, 'name' => 'reviewer', 'description' => 'Content Reviewer', 'created_at' => '2025-10-19 08:55:02', 'updated_at' => '2025-10-19 08:55:02'],
            ['id' => 3, 'name' => 'author', 'description' => 'Author Content', 'created_at' => '2025-10-19 08:55:02', 'updated_at' => '2025-10-19 08:55:02'],
        ]);


        DB::table('users')->insert([
            [
                'id' => 1,
                'name' => 'joe',
                'email' => 'example@test.ru',
                'password' => Hash::make('password'),
                'role_id' => 1,
                'bio' => 'bio',
                'avatar' => null,
                'preferences' => json_encode(['favorites' => [22]]),
                'github_id' => null,
                'github_token' => null,
                'github_refresh_token' => null,
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => null,
                'created_at' => '2025-10-02 07:21:54',
                'updated_at' => '2026-03-19 03:05:41',
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'name' => 'doe',
                'email' => 'test@test.ru',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'bio' => '',
                'avatar' => 'storage/images/avatars/avatar_3_1772098729.jpg',
                'preferences' => json_encode(['favorites' => [22]]),
                'github_id' => null,
                'github_token' => null,
                'github_refresh_token' => null,
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => null,
                'created_at' => '2025-10-15 02:23:04',
                'updated_at' => '2026-02-26 04:42:20',
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'name' => 'Слава кпсс',
                'email' => 'bonaqua@yandex.ru',
                'password' => Hash::make('password'),
                'role_id' => 3,
                'bio' => 'asdbaksjdjasdzxz',
                'avatar' => 'avatars/user_4/1773218798_69b12bee13587.jpg',
                'preferences' => json_encode(['favorites' => [22, 20, 16, 5, 8, 3, 1, 4]]),
                'github_id' => null,
                'github_token' => null,
                'github_refresh_token' => null,
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => null,
                'created_at' => '2025-10-26 07:09:12',
                'updated_at' => '2026-06-09 03:58:51',
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'name' => 'Joe',
                'email' => 'example@test1.ru',
                'password' => Hash::make('password'),
                'role_id' => 3,
                'bio' => 'о себе',
                'avatar' => 'avatars/user_5/1780995943_6a27d76701064.jpg',
                'preferences' => json_encode(['favorites' => [20, 22, 4]]),
                'github_id' => null,
                'github_token' => null,
                'github_refresh_token' => null,
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => null,
                'created_at' => '2025-11-24 08:05:35',
                'updated_at' => '2026-06-09 04:06:01',
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'name' => 'Joe',
                'email' => 'exampl1e@test.ru',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'bio' => 'bio',
                'avatar' => 'storage/images/avatars/avatar_7_1764574408.png',
                'preferences' => json_encode(['favorites' => []]),
                'github_id' => null,
                'github_token' => null,
                'github_refresh_token' => null,
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => null,
                'created_at' => '2025-12-01 02:32:52',
                'updated_at' => '2025-12-01 02:35:40',
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'name' => 'gdsg',
                'email' => 'test@rrsdf.dfd',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'bio' => 'cx',
                'avatar' => 'storage/images/avatars/avatar_8_1765013268.jpg',
                'preferences' => json_encode(['favorites' => [22]]),
                'github_id' => null,
                'github_token' => null,
                'github_refresh_token' => null,
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => null,
                'created_at' => '2025-12-06 04:27:09',
                'updated_at' => '2025-12-06 04:28:11',
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'name' => 'Ghosy',
                'email' => 'mc@example.ru',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'bio' => null,
                'avatar' => null,
                'preferences' => null,
                'github_id' => null,
                'github_token' => null,
                'github_refresh_token' => null,
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => null,
                'created_at' => '2025-12-29 07:40:33',
                'updated_at' => '2025-12-29 07:40:33',
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'name' => 'Ghosy',
                'email' => 'mc@exampile.ru',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'bio' => null,
                'avatar' => null,
                'preferences' => null,
                'github_id' => null,
                'github_token' => null,
                'github_refresh_token' => null,
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => null,
                'created_at' => '2026-01-06 07:32:53',
                'updated_at' => '2026-01-06 07:32:53',
                'deleted_at' => null,
            ],
            [
                'id' => 15,
                'name' => 'fedor',
                'email' => 'qwerbv@gmail.com',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'bio' => null,
                'avatar' => null,
                'preferences' => null,
                'github_id' => null,
                'github_token' => null,
                'github_refresh_token' => null,
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => null,
                'created_at' => '2026-03-07 07:27:19',
                'updated_at' => '2026-03-07 07:27:19',
                'deleted_at' => null,
            ],
            [
                'id' => 16,
                'name' => 'wqewqr',
                'email' => 'qwesda@asd.ru',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'bio' => null,
                'avatar' => null,
                'preferences' => null,
                'github_id' => null,
                'github_token' => null,
                'github_refresh_token' => null,
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => null,
                'created_at' => '2026-03-07 07:38:23',
                'updated_at' => '2026-03-07 07:38:23',
                'deleted_at' => null,
            ],
            [
                'id' => 17,
                'name' => 'qwedsa',
                'email' => 'asdfqwd@sadsad.ru',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'bio' => null,
                'avatar' => null,
                'preferences' => null,
                'github_id' => null,
                'github_token' => null,
                'github_refresh_token' => null,
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => null,
                'created_at' => '2026-03-07 08:12:53',
                'updated_at' => '2026-03-07 08:12:53',
                'deleted_at' => null,
            ],
            [
                'id' => 18,
                'name' => 'wqeqe',
                'email' => 'wqeqe@das.ru',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'bio' => null,
                'avatar' => null,
                'preferences' => null,
                'github_id' => null,
                'github_token' => null,
                'github_refresh_token' => null,
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => null,
                'created_at' => '2026-03-07 08:24:05',
                'updated_at' => '2026-03-07 08:24:05',
                'deleted_at' => null,
            ],
            [
                'id' => 19,
                'name' => 'wqeqxczc',
                'email' => 'wqe22qe@das.ru',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'bio' => null,
                'avatar' => null,
                'preferences' => null,
                'github_id' => null,
                'github_token' => null,
                'github_refresh_token' => null,
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => null,
                'created_at' => '2026-03-07 08:24:49',
                'updated_at' => '2026-03-07 08:24:49',
                'deleted_at' => null,
            ],
            [
                'id' => 20,
                'name' => 'wqe22q222',
                'email' => 'wqe22q21e@das.ru',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'bio' => null,
                'avatar' => null,
                'preferences' => null,
                'github_id' => null,
                'github_token' => null,
                'github_refresh_token' => null,
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => null,
                'created_at' => '2026-03-07 08:31:54',
                'updated_at' => '2026-03-07 08:31:54',
                'deleted_at' => null,
            ],
            [
                'id' => 21,
                'name' => 'adafas',
                'email' => 'adafas@qwd.ry',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'bio' => null,
                'avatar' => null,
                'preferences' => null,
                'github_id' => null,
                'github_token' => null,
                'github_refresh_token' => null,
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => null,
                'created_at' => '2026-03-07 08:39:38',
                'updated_at' => '2026-03-07 08:39:38',
                'deleted_at' => null,
            ],
            [
                'id' => 31,
                'name' => 'Joe',
                'email' => 'Joe@example.com',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'bio' => null,
                'avatar' => null,
                'preferences' => null,
                'github_id' => null,
                'github_token' => null,
                'github_refresh_token' => null,
                'google_id' => null,
                'google_token' => null,
                'google_refresh_token' => null,
                'remember_token' => null,
                'created_at' => '2026-04-14 07:20:14',
                'updated_at' => '2026-04-14 07:20:14',
                'deleted_at' => null,
            ],
        ]);


        DB::table('contents')->insert([
            [
                'id' => 4,
                'title' => 'Друг',
                'music_type' => 'single',
                'artist' => 'SLAWA MARLOW, Арлен',
                'genre' => 'Hip-Hop',
                'release_date' => '2024-06-14',
                'cover_image' => 'covers/content_4/1780659365_6a22b4a52be9f.jpeg',
                'label' => 'Sunset Records',
                'favorites_count' => 180,
                'reviews_count' => 0,
                'added_by' => 1,
                'created_at' => '2025-10-06 04:26:32',
                'updated_at' => '2026-06-09 04:06:01',
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'title' => 'Пропадаю я',
                'music_type' => 'single',
                'artist' => 'MAYOT, Любовь Успенская',
                'genre' => 'Hip-Hop',
                'release_date' => '2024-04-22',
                'cover_image' => 'covers/content_5/1780926982_6a26ca067f577.jpeg',
                'label' => 'Galaxy Music',
                'favorites_count' => 70,
                'reviews_count' => 0,
                'added_by' => 1,
                'created_at' => '2025-10-06 04:26:32',
                'updated_at' => '2026-06-09 03:55:54',
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'title' => 'Ранетки',
                'music_type' => 'single',
                'artist' => 'ROCKET',
                'genre' => 'Ambient',
                'release_date' => '2024-05-30',
                'cover_image' => 'covers/content_6/1780926948_6a26c9e418157.jpeg',
                'label' => 'Atmosphere Label',
                'favorites_count' => 45,
                'reviews_count' => 0,
                'added_by' => 1,
                'created_at' => '2025-10-06 04:26:32',
                'updated_at' => '2026-06-08 08:55:48',
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'title' => 'КАТАРСИС',
                'music_type' => 'album',
                'artist' => 'clout',
                'genre' => 'Folk',
                'release_date' => '2024-07-12',
                'cover_image' => 'covers/content_8/1780659341_6a22b48d49b9f.jpeg',
                'label' => 'Earth Tones',
                'favorites_count' => 79,
                'reviews_count' => 0,
                'added_by' => 1,
                'created_at' => '2025-10-06 04:26:32',
                'updated_at' => '2026-06-05 06:35:41',
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'title' => 'SENSATION! A Cute Chaotic Trail',
                'music_type' => 'album',
                'artist' => 'Baby Cute',
                'genre' => 'R&B',
                'release_date' => '2024-01-06',
                'cover_image' => 'covers/content_10/1780933647_6a26e40fc174b.jpeg',
                'label' => 'Radiant Music',
                'favorites_count' => 201,
                'reviews_count' => 1,
                'added_by' => 1,
                'created_at' => '2025-10-06 04:26:32',
                'updated_at' => '2026-06-08 10:47:33',
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'title' => '200K',
                'music_type' => 'album',
                'artist' => 'Baby Cute',
                'genre' => 'Synthpop',
                'release_date' => '2024-01-15',
                'cover_image' => 'covers/content_11/1780927874_6a26cd823678e.jpeg',
                'label' => '80s Revival',
                'favorites_count' => 145,
                'reviews_count' => 0,
                'added_by' => 1,
                'created_at' => '2025-10-06 04:26:32',
                'updated_at' => '2026-06-08 09:11:15',
                'deleted_at' => null,
            ],
            [
                'id' => 16,
                'title' => 'Призраки Фантьета',
                'music_type' => 'album',
                'artist' => 'Ежемесячные',
                'genre' => 'Rap',
                'release_date' => '2024-10-04',
                'cover_image' => 'covers/content_16/1780659215_6a22b40fc58ba.jpg',
                'label' => 'Space Music',
                'favorites_count' => 89,
                'reviews_count' => 0,
                'added_by' => 1,
                'created_at' => '2025-10-06 04:26:32',
                'updated_at' => '2026-06-05 06:33:38',
                'deleted_at' => null,
            ],
            [
                'id' => 19,
                'title' => 'sv moscow',
                'music_type' => 'EP',
                'artist' => 'королевский XVII',
                'genre' => 'Alternative',
                'release_date' => '2024-07-30',
                'cover_image' => 'covers/content_19/1780659310_6a22b46ee5921.jpeg',
                'label' => 'City Records',
                'favorites_count' => 98,
                'reviews_count' => 0,
                'added_by' => 1,
                'created_at' => '2025-10-06 04:26:32',
                'updated_at' => '2026-06-08 11:09:13',
                'deleted_at' => null,
            ],
            [
                'id' => 20,
                'title' => 'Мементо мори',
                'music_type' => 'album',
                'artist' => 'Овсянкин',
                'genre' => 'Rap',
                'release_date' => '2024-11-05',
                'cover_image' => 'covers/content_20/1780659153_6a22b3d1d95e2.jpg',
                'label' => 'The Fence',
                'favorites_count' => 158,
                'reviews_count' => 0,
                'added_by' => 1,
                'created_at' => '2025-10-06 04:26:32',
                'updated_at' => '2026-06-05 06:32:35',
                'deleted_at' => null,
            ],
            [
                'id' => 22,
                'title' => 'ОТТЕНКИ БАРДА 2',
                'music_type' => 'album',
                'artist' => 'СЛАВА КПСС',
                'genre' => 'Rap',
                'release_date' => '2025-11-28',
                'cover_image' => 'covers/content_22/1773910100_69bbb854290f8.jpg',
                'label' => 'The Fence',
                'favorites_count' => 6,
                'reviews_count' => 1,
                'added_by' => 1,
                'created_at' => '2025-10-10 01:45:17',
                'updated_at' => '2026-04-10 08:53:25',
                'deleted_at' => null,
            ],
            [
                'id' => 28,
                'title' => 'Аниме средней полосы',
                'music_type' => 'album',
                'artist' => 'Максим Плакин',
                'genre' => 'Rap',
                'release_date' => '2026-03-05',
                'cover_image' => 'covers/content_28/1780933893_6a26e5055f0ed.jpeg',
                'label' => 'Воскресная школа',
                'favorites_count' => 0,
                'reviews_count' => 0,
                'added_by' => 1,
                'created_at' => '2026-06-08 10:51:33',
                'updated_at' => '2026-06-08 10:51:33',
                'deleted_at' => null,
            ],
            [
                'id' => 29,
                'title' => 'Институт',
                'music_type' => 'single',
                'artist' => 'issey',
                'genre' => 'Pop',
                'release_date' => '2026-01-10',
                'cover_image' => 'covers/content_29/1780933966_6a26e54ecd17d.jpeg',
                'label' => 'Unki',
                'favorites_count' => 0,
                'reviews_count' => 0,
                'added_by' => 1,
                'created_at' => '2026-06-08 10:52:46',
                'updated_at' => '2026-06-08 10:52:48',
                'deleted_at' => null,
            ],
            [
                'id' => 30,
                'title' => 'Мысли',
                'music_type' => 'EP',
                'artist' => 'KRISTIEE',
                'genre' => 'Hip-Hop',
                'release_date' => '2025-08-14',
                'cover_image' => 'covers/content_30/1780934137_6a26e5f9761bf.jpeg',
                'label' => 'BandLink',
                'favorites_count' => 0,
                'reviews_count' => 0,
                'added_by' => 1,
                'created_at' => '2026-06-08 10:55:37',
                'updated_at' => '2026-06-08 11:09:29',
                'deleted_at' => null,
            ],
            [
                'id' => 31,
                'title' => 'Garden of Eden',
                'music_type' => 'EP',
                'artist' => 'KADI',
                'genre' => 'Jazz',
                'release_date' => '2026-05-06',
                'cover_image' => 'covers/content_31/1780934288_6a26e69098334.jpeg',
                'label' => 'JazzDoIt',
                'favorites_count' => 0,
                'reviews_count' => 0,
                'added_by' => 1,
                'created_at' => '2026-06-08 10:58:08',
                'updated_at' => '2026-06-08 11:09:06',
                'deleted_at' => null,
            ],
            [
                'id' => 32,
                'title' => 'VELIAL CLUB',
                'music_type' => 'album',
                'artist' => 'VELIAL SQUAD',
                'genre' => 'Hip-Hop',
                'release_date' => '2026-06-05',
                'cover_image' => 'covers/content_32/1780934355_6a26e6d3789ab.png',
                'label' => 'The Fence',
                'favorites_count' => 0,
                'reviews_count' => 0,
                'added_by' => 1,
                'created_at' => '2026-06-08 10:59:15',
                'updated_at' => '2026-06-08 10:59:19',
                'deleted_at' => null,
            ],
        ]);


        DB::table('reviews')->insert([
            [
                'id' => 3,
                'content_id' => 22,
                'user_id' => 1,
                'title' => 'Шедевральный альбом!',
                'text' => 'Этот альбом просто потрясающий! Каждый трек - отдельная история. Особенно впечатлила работа ударных и глубокие тексты. Альбом будет играть у меня на повторе еще очень долго!',
                'created_at' => '2025-10-26 12:11:43',
                'updated_at' => '2026-04-10 09:20:22',
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'content_id' => 10,
                'user_id' => 4,
                'title' => '«Golden Hour»: Три минуты чистого солнца',
                'text' => 'Новый сингл «Golden Hour» — это именно тот звук, который ждешь от лета 2024. С первых же секунд трек окутывает теплым, сияющим звучанием: томные синтезаторы, мерцающие электронные биты и парящий вокал, который словно растворяется в закатном небе.\n\nЭто идеальный саундтрек для момента, когда солнце касается горизонта, а мир залит золотым светом. Композиция не стремится удивить сложностью, ее сила — в безупречной атмосфере и запоминающемся хуке. «Golden Hour» — это три минуты безмятежного побега, маленький аудиальный отпуск, который хочется ставить на повтор.',
                'created_at' => '2025-11-30 08:44:24',
                'updated_at' => '2025-11-30 08:44:24',
                'deleted_at' => null,
            ],
            [
                'id' => 14,
                'content_id' => 16,
                'user_id' => 1,
                'title' => 'Альбом из джунглей',
                'text' => 'Уже третий альбом, еже сделанный с взглядом на конкретную страну. В этот раз ей стал Вьетнам\nТекст на крепкую 10, из-за обилия слов, редко используемых в обычном русском языке, а также культурных и географических названий из Вьетнама получается огромное количество уникальных рифм, которые навряд ли встретятся где-то еще. Сами образы тоже неплохи, на протяжении всего альбома была лёгкая улыбка\nК структуре каждого отдельного трека вопросов нет — они пролетают быстро, но альбом в целом слушать тяжело, довольно однообразные биты и читка, а также скит на 6 минут в конце\nПо реализации сказать особо нечего, артисты исполнили весьма неплохо, за альбом не было прям плохих партов, но биты довольно однообразные, и хотя они разнообразятся инструменталом, многие треки звучат в голове одинаково',
                'created_at' => '2025-12-06 03:36:50',
                'updated_at' => '2026-04-11 00:28:09',
                'deleted_at' => null,
            ],
            [
                'id' => 37,
                'content_id' => 4,
                'user_id' => 4,
                'title' => 'Великолепно',
                'text' => 'Даже не смогу описать чувства которые вызывает данная песня. Самая лучшая работа Славы, У Славы и Арлена прям похожие голоса и это звучит просто отлично, начало песни очень атмосферно, Арлен спел тоже великолепно, настоящая песня дружбы. Просто послушайте и поймете что это исскуство. Видел видео РЗТ и полностью соглашусь что обложка здесь максимально не подходит, сцена с костром в начале клипа которая была, даже лучше бы подошла.\nИнструментал на высоте, а как артисты тянут слова и гласные это звучит очень нежно и приятно. Спасибо Слава И Арлен!\nВсем добра!',
                'created_at' => '2026-06-09 03:57:56',
                'updated_at' => '2026-06-09 03:57:56',
                'deleted_at' => null,
            ],
            [
                'id' => 38,
                'content_id' => 4,
                'user_id' => 5,
                'title' => 'В шоке.',
                'text' => 'В первую очередь хочу отметить инструментал, на контрасте с карьерой Славы битмейкера - это звучит мягко говоря необычно. Инструментал на высшем уровне.\nСтиль, харизма - браво, вышло сдержанно, гармонично и попсово. Из-за поп звучания минус к индивидуальности, подобные мелодии инструментала и подобное пение мы уже слышали тысячу раз, однако, такое давно не происходило в современном искусстве, от современных исполнителей.\nСтруктура/Ритмика очень хороши, где хороший инструментал - там и хороший ритм, где хороший ритм - там и за частую хорошая структура, ни добавить, ни убавить.\nРифмы и образы не напряжённые, лёгкие, лирика отлично ложится на инструменты. Лично мне не хватило больше образов в виде ассоциативных метафор.\nЗа атмосферу/вайб всё так же, ясно, выше были упоминания связанные с общей атмосферой собранной из отличного вокала и инструментала. Композиция идеально передает крепкие дружеские чувства и эмоции, вызывая в сердце чувство \"братской\" любви, уважения и доверия по отношению к другу. Она напоминает нам, о том, чем является дружба, говорит о том самом друге, в котором ты можешь быть уверенным и с которым ты можешь вместе идти следуя своим судьбам, путям и мечтам, никогда не забывая его.',
                'created_at' => '2026-06-09 04:04:55',
                'updated_at' => '2026-06-09 04:04:55',
                'deleted_at' => null,
            ],
        ]);

        DB::table('review_likes')->insert([
            ['reviews_id' => 3, 'user_id' => 7, 'type' => 'like', 'created_at' => '2025-12-01 02:34:50', 'updated_at' => '2025-12-01 02:34:50'],
            ['reviews_id' => 3, 'user_id' => 4, 'type' => 'author_like', 'created_at' => '2026-03-13 09:02:11', 'updated_at' => '2026-03-13 09:02:11'],
            ['reviews_id' => 3, 'user_id' => 1, 'type' => 'like', 'created_at' => '2026-03-19 03:48:32', 'updated_at' => '2026-03-19 03:48:32'],
            ['reviews_id' => 3, 'user_id' => 5, 'type' => 'author_like', 'created_at' => '2026-04-10 08:51:14', 'updated_at' => '2026-04-10 08:51:14'],
            ['reviews_id' => 11, 'user_id' => 4, 'type' => 'author_like', 'created_at' => '2026-06-09 04:02:05', 'updated_at' => '2026-06-09 04:02:05'],
            ['reviews_id' => 37, 'user_id' => 5, 'type' => 'author_like', 'created_at' => '2026-06-09 04:05:15', 'updated_at' => '2026-06-09 04:05:15'],
            ['reviews_id' => 38, 'user_id' => 5, 'type' => 'author_like', 'created_at' => '2026-06-09 04:05:09', 'updated_at' => '2026-06-09 04:05:09'],
        ]);
    }
}